name: Test

on:
  push:

jobs:
  run-make-check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/yaccz/debian-11-sh-toolchain
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - uses: actions/checkout@v3
      - name: Run make check
        run: make check

  run-make-check-macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: setup
        run: sh bin/setup-macos.sh

      - name: Run make check
        run: make check
